language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t xeo4it/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true xeo4it/react-test npm test

after_success:
    - docker build -t dongimmi/multi-client ./client
    - docker build -t dongimmi/multi-nginx ./nginx
    - docker build -t dongimmi/multi-server ./server
    - docker build -t dongimmi/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push dongimmi/multi-client
    - docker push dongimmi/multi-nginx
    - docker push dongimmi/multi-server
    - docker push dongimmi/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-450375530402"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY    